query DayEntries($from: Date, $to: Date) {
  dayEntries(sort: "day", filters: { day: { gte: $from, lte: $to } }, pagination: { limit: 100 }) {
    data {
      id
      attributes {
        hours
        paid
        day
      }
    }
  }
}